steps:
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speakease-api'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/speakease/speakease-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--port'
      - '8010'
      - '--ingress'
      - 'all'
      - '--service-account'
      - 'lingoforge@gcpxmlb25.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=gcpxmlb25,PYTHONPATH=/app'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '80'
      - '--execution-environment'
      - 'gen2' 